name: 'FTP Deploy'

on: workflow_dispatch

jobs:
  deploy:
    name: 'Deploying'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 141.8.192.193
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
